// v20.0: category pagination + daily reset + strong seed
const $=s=>document.querySelector(s);
const titleBox=$("#title"),blurbBox=$("#blurb"),genreSel=$("#genreSel");
const detailBtn=$("#detailBtn"),relatedBtn=$("#relatedBtn"),openBtn=$("#openBtn"),
      nextBtn=$("#nextBtn"),backBtn=$("#backBtn"),clearBtn=$("#clearBtn"),
      maintext=$("#maintext"),altview=$("#altview");
let current=null;const V='v20_0',SEEN_KEY='siren_seen_titles_'+V,DAY_KEY='siren_seen_day_'+V,CURSOR_KEY='siren_cat_cursor_'+V,SEEN_LIMIT=1e5;
function loadJ(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function saveJ(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function day(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
let seenSet=new Set((()=>{const ld=localStorage.getItem(DAY_KEY),nd=day();if(ld!==nd){const pv=loadJ(SEEN_KEY,[]);saveJ(SEEN_KEY,pv.slice(-5e3));localStorage.setItem(DAY_KEY,nd)}return loadJ(SEEN_KEY,[])} )());
function saveSeen(){if(seenSet.size>SEEN_LIMIT){seenSet=new Set(Array.from(seenSet).slice(-8e4))}saveJ(SEEN_KEY,Array.from(seenSet))}
let curs=loadJ(CURSOR_KEY,{});const getCur=g=>curs[g]||"";const setCur=(g,t)=>{curs[g]=t||"";saveJ(CURSOR_KEY,curs)};
async function sSeed(){const n=Math.floor(Date.now()/1e3),p=(performance.now()*1e3|0)&4294967295,r=crypto.getRandomValues(new Uint32Array(2)),u=navigator.userAgent,b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${n}|${p}|${r[0]}|${r[1]}|${u}`));const dv=new DataView(b);return(BigInt(dv.getUint32(0))<<32n)|BigInt(dv.getUint32(4))}
function m32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffle(a,s){const r=m32(Number(s&0xffffffffn)||1);for(let i=a.length-1;i>0;i--){const j=(r()*(i+1))|0;[a[i],a[j]]=[a[j],a[i]]}return a}
function bust(u){return u+(u.includes('?')?'&':'?')+'t='+Date.now()}
async function jget(u){const res=await fetch(bust(u),{mode:'cors',headers:{'Accept':'application/json'},cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const ct=res.headers.get('content-type')||'';if(!ct.includes('application/json'))throw new Error('Non-JSON');return res.json()}
function norm(d){const t=d.title||'（無題）',bl=d.description?`${d.description}`:(d.extract?(d.extract.split('。')[0]+'。'):'（概要なし）');const det=d.extract||'（詳細なし）';const url=(d.content_urls&&d.content_urls.desktop)?d.content_urls.desktop.page:('https://ja.wikipedia.org/wiki/'+encodeURIComponent(t));return {title:t,blurb:bl,detail:det,url}}
async function catBatch(cat,cmc=""){const u='https://ja.wikipedia.org/w/api.php?action=query&format=json&list=categorymembers&cmtitle='+encodeURIComponent('Category:'+cat)+'&cmtype=page&cmnamespace=0&cmlimit=100&origin=*'+(cmc?('&cmcontinue='+encodeURIComponent(cmc)):'');const d=await jget(u);const m=(d.query&&d.query.categorymembers)||[];const cont=(d.continue&&d.continue.cmcontinue)||"";return {titles:m.map(x=>x.title),cont}}
async function titlesPaged(g,seed,need=80){let acc=[],cur=getCur(g);for(let i=0;i<6&&acc.length<need;i++){const {titles,cont}=await catBatch(g,cur);if(!titles.length&&!cont){cur="";setCur(g,cur);break}acc.push(...titles);cur=cont||"";setCur(g,cur);acc=shuffle(acc,seed+BigInt(i))}acc=acc.filter(t=>!seenSet.has(t));shuffle(acc,seed^0x9abcdn);return acc}
async function rndTitles(n=60){const d=await jget('https://ja.wikipedia.org/w/api.php?action=query&format=json&list=random&rnnamespace=0&rnlimit='+n+'&origin=*');return ((d.query&&d.query.random)||[]).map(x=>x.title)}
async function sumByTitle(t){return norm(await jget('https://ja.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(t)))}
async function relRobust(t){try{const d=await jget('https://ja.wikipedia.org/api/rest_v1/page/related/'+encodeURIComponent(t));const r=(d.pages||[]).map(norm);if(r&&r.length)return r}catch{}try{const d=await jget('https://ja.wikipedia.org/w/api.php?action=query&format=json&list=search&srsearch='+encodeURIComponent('morelike:\"'+t+'\"')+'&srlimit=9&srnamespace=0&origin=*');const hits=(d.query&&d.query.search)||[];const ts=hits.map(h=>h.title).filter(Boolean);const out=[];for(const x of ts){try{out.push(await sumByTitle(x))}catch{}}if(out.length)return out}catch{}try{const d=await jget('https://ja.wikipedia.org/w/api.php?action=parse&format=json&page='+encodeURIComponent(t)+'&prop=links&origin=*');const links=(d.parse&&d.parse.links)||[];const ts=links.filter(l=>l.ns===0&&l['*']).slice(0,12).map(l=>l['*']);const out=[];for(const x of ts){try{out.push(await sumByTitle(x))}catch{}}if(out.length)return out}catch{}try{const d=await jget('https://ja.wikipedia.org/w/api.php?action=opensearch&format=json&search='+encodeURIComponent(t)+'&limit=9&namespace=0&origin=*');const ts=Array.isArray(d)&&Array.isArray(d[1])?d[1]:[];const out=[];for(const x of ts){try{out.push(await sumByTitle(x))}catch{}}if(out.length)return out}catch{}try{const d=await jget('https://ja.wikipedia.org/w/api.php?action=query&format=json&prop=categories&clshow=!hidden&titles='+encodeURIComponent(t)+'&origin=*');const pages=d.query&&d.query.pages?Object.values(d.query.pages):[];const cats=pages.length?(pages[0].categories||[]):[];if(cats.length){const cat=cats[0].title;const d2=await jget('https://ja.wikipedia.org/w/api.php?action=query&format=json&list=categorymembers&cmtitle='+encodeURIComponent(cat)+'&cmtype=page&cmnamespace=0&cmlimit=9&origin=*');const mem=(d2.query&&d2.query.categorymembers)||[];const ts=mem.map(m=>m.title).filter(Boolean);const out=[];for(const x of ts){try{out.push(await sumByTitle(x))}catch{}}if(out.length)return out}}catch{}return []}
function showMain(){maintext.hidden=false;altview.hidden=true;backBtn.hidden=true}
function showAlt(h){altview.innerHTML=h;maintext.hidden=true;altview.hidden=false;backBtn.hidden=false}
function renderMain(s){titleBox.textContent=`【 ${s.title} 】`;blurbBox.textContent=s.blurb;showMain()}
async function pickNew(){const g=genreSel.value;const seed=await sSeed();let ts=[];if(g==='all'){ts=(await rndTitles(60)).filter(t=>!seenSet.has(t));shuffle(ts,seed)}else{ts=await titlesPaged(g,seed,80)}let tries=0;while(ts.length===0&&tries<4){tries++;if(g!=='all'){setCur(g,"");ts=await titlesPaged(g,seed+BigInt(tries),80)}if(ts.length===0){const mix=await rndTitles(60);shuffle(mix,seed+BigInt(256*tries));ts=mix.filter(t=>!seenSet.has(t))}}if(!ts.length)return null;return await sumByTitle(ts[0])}
async function showOne(){const s=await pickNew();if(!s){titleBox.textContent='（候補が見つかりません）';blurbBox.textContent='ジャンルを変えるか、少し時間をおいて再試行してください。';showMain();return}current=s;seenSet.add(s.title);saveSeen();renderMain(s)}
$("#detailBtn").addEventListener('click',()=>{if(!current)return;showAlt(`<h3>DETAIL</h3>${esc(current.detail)}\n\n<p><a href="${current.url}" target="_blank" rel="noopener">WIKIを開く</a></p>`)});
$("#relatedBtn").addEventListener('click',async()=>{if(!current)return;showAlt("<h3>RELATED</h3><ul><li>loading…</li></ul>");try{const rel=await relRobust(current.title);if(!rel.length){showAlt("<h3>RELATED</h3><ul><li>(no items)</li></ul>");return}const items=rel.slice(0,9).map((p,i)=>`<li>[${i+1}] <a href="${p.url}" target="_blank" rel="noopener">${esc(p.title)}</a></li>`).join("");showAlt(`<h3>RELATED</h3><ul>${items}</ul>`)}catch{showAlt("<h3>RELATED</h3><ul><li>(failed)</li></ul>")}});
$("#openBtn").addEventListener('click',()=>{const u=current?.url||(current?.title?('https://ja.wikipedia.org/wiki/'+encodeURIComponent(current.title)):null);if(u)window.open(u,'_blank','noopener')});
$("#nextBtn").addEventListener('click',()=>{showOne()});$("#backBtn").addEventListener('click',()=>{showMain()});$("#clearBtn").addEventListener('click',()=>{if(!altview.hidden)showMain()});
setTimeout(()=>{showOne()},400);
if(location.protocol.startsWith('http')&&'serviceWorker'in navigator){navigator.serviceWorker.register('./serviceWorker.js').then(r=>{if(r&&r.update)r.update()}).catch(()=>{})}
function esc(s){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;','\\'':'&#39;'}[m]))}
